user_database:
  image: mariadb:10
  container_name: userdb
  ports:
   - "3301:3306"
  environment:
   - "constraint:node==mhs-demo1"
  environment:
   MYSQL_ROOT_PASSWORD: sius_es
   MYSQL_USER: sius
   MYSQL_PASSWORD: sius_es
   MYSQL_DATABASE: events_users
  net: "my-net"

event_database:
  image: mariadb:10
  container_name: eventdb
  ports:
   - "3302:3306"
  environment:
   - "constraint:node==mhs-demo1"
  environment:
   MYSQL_ROOT_PASSWORD: sius_es
   MYSQL_USER: sius
   MYSQL_PASSWORD: sius_es
   MYSQL_DATABASE: events_system
  net: "my-net"
